tox set-up 22000

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -12,7 +12,7 @@ jobs:
     steps:
       - uses: actions/checkout@v4
         with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+          fetch-depth: 0  # Shallow clones should be disabled for better analysis relevancy
 
       - name: Setup Python
         uses: actions/setup-python@v2
@@ -27,8 +27,25 @@ jobs:
 
       - name: Install tox and any other packages
         run: pip install tox
+
       - name: Run tox
         run: tox -e py
+
+      # Wait and check for coverage.xml
+      - name: Wait for coverage.xml
+        run: |
+          echo "Waiting for coverage.xml to be created..."
+          timeout=0
+          while [ ! -f coverage.xml ]; do
+            sleep 2
+            timeout=$((timeout + 1))
+            if [ $timeout -gt 30 ]; then
+              echo "coverage.xml not found after waiting 60 seconds. Exiting."
+              exit 1
+            fi
+          done
+          echo "coverage.xml found!"
+
       - name: SonarCloud Scan
         uses: SonarSource/sonarcloud-github-action@master
         env:
