test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -21,7 +21,26 @@ jobs:
         run: pip install tox
       - name: Run tox
         run: tox -e py
+      # Wait and check for coverage.xml
+      - name: Wait for coverage.xml
+        run: |
+          echo "Waiting for coverage.xml to be created..."
+          timeout=0
+          while [ ! -f coverage.xml ]; do
+            sleep 2
+            timeout=$((timeout + 1))
+            if [ $timeout -gt 30 ]; then
+              echo "coverage.xml not found after waiting 60 seconds. Exiting."
+              exit 1
+            fi
+          done
+          echo "coverage.xml found!"
       - name: SonarCloud Scan
         uses: SonarSource/sonarcloud-github-action@master
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        with:
+          args: >
+            -Dsonar.python.coverage.reportPaths=coverage.xml
+            -Dsonar.tests=tests/
+            -Dsonar.verbose=true
